### PR TITLE
Added support for Laravel 9 and bensampo/laravel-enum version 5

### PR DESCRIPTION
**Pull request by dees040**

### CODE REVIEW

**Comment by eclipse313** [comment]
Please merge: the tests fail only because of the Nova repository. I tested it and it works perfectly under Laravel 9

**Comment by mdpoulter** [comment]
The GitHub actions will also need to be updated, so I will make these updates later today or tomorrow.

**Comment by dees040** [comment]
Hey @mdpoulter,  any update on this matter? Thanks.

**Comment by mdpoulter** [comment]
@dees040 Yes, [joshgaber/NovaUnit](https://github.com/joshgaber/NovaUnit) v2.3 has been tagged with Laravel 9 support, so I will get on this tomorrow.

**Pull request closed without merging**
