### PR TITLE
Upgrade to Laravel 11

### PR DESCRIPTION
**Pull request by mdpoulter**
Delayed until https://github.com/joshgaber/NovaUnit/pull/64 is merged.

### CODE REVIEW

**Comment by remxcode** [comment]
Hi! Can you merge this commit and publish this new version? Thanks~

**Comment by mdpoulter** [comment]
Hi @remxcode . As mentioned in the description, we are waiting for a required package to be updated first before we can merge this.

**Comment by mdpoulter** [comment]
Yes, it looks like there's a fork of the testing package we use, so I'm going to look at swapping to that this weekend (unless anyone wants to submit a PR before then 😀)

**Comment by couchlab-pl** [comment]
thanks, waiting

**Pull request merged**
